# Generated by Django 6.0.6 on 2026-06-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_sessions', '0002_alter_chatsession_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatsession',
            name='chat_sessio_user_id_54b88f_idx',
        ),
    ]
