# Generated by Django 6.0.6 on 2026-06-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_alter_budget_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='budget',
            name='budgets_user_id_300e09_idx',
        ),
    ]
