# Generated by Django 6.0.6 on 2026-06-05 04:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'USER'), ('ASSISTANT', 'ASSISTANT')], default='USER', max_length=20)),
                ('content', models.TextField()),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat_sessions.chatsession')),
            ],
            options={
                'db_table': 'chat_messages',
                'indexes': [models.Index(fields=['session'], name='chat_messag_session_70d2c0_idx')],
            },
        ),
    ]
