# Generated by Django 6.0.6 on 2026-06-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0002_alter_chatmessage_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='chat_messag_session_70d2c0_idx',
        ),
    ]
