# Generated by Django 6.0.6 on 2026-06-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='account',
            name='accounts_user_id_6786b5_idx',
        ),
    ]
