# Generated by Django 6.0.6 on 2026-06-05 04:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('chat_receipts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INCOME', 'INCOME'), ('EXPENSE', 'EXPENSE'), ('TRANSFER', 'TRANSFER')], db_index=True, default='EXPENSE', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('source', models.CharField(choices=[('MANUAL', 'MANUAL'), ('CSV', 'CSV'), ('MOCK_BANK', 'MOCK_BANK'), ('RECEIPT', 'RECEIPT'), ('ASSISTANT', 'ASSISTANT')], default='CSV', max_length=20)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('merchant', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.account')),
                ('receipt', models.ForeignKey(blank=True, db_column='receipt_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='chat_receipts.receipt')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.user')),
            ],
            options={
                'db_table': 'transactions',
                'indexes': [models.Index(fields=['user'], name='transaction_user_id_b5bcfd_idx'), models.Index(fields=['account'], name='transaction_account_d84ffe_idx'), models.Index(fields=['receipt'], name='transaction_receipt_23f278_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'source', 'external_id'), name='uq_user_source_external_id')],
            },
        ),
    ]
