# Generated by Django 6.0.6 on 2026-06-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_user_id_b5bcfd_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_account_d84ffe_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_receipt_23f278_idx',
        ),
    ]
