# Generated by Django 6.0.6 on 2026-06-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_context', '0002_alter_usercontext_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usercontext',
            name='user_contex_user_id_2b60d3_idx',
        ),
    ]
