# Generated by Django 6.0.6 on 2026-06-05 04:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('PROCESSING', 'PROCESSING'), ('PROCESSED', 'PROCESSED'), ('FAILED', 'FAILED'), ('NEEDS_REVIEW', 'NEEDS_REVIEW')], default='PROCESSING', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='users.user')),
            ],
            options={
                'db_table': 'receipts',
                'indexes': [models.Index(fields=['user'], name='receipts_user_id_1887b7_idx')],
            },
        ),
    ]
